version: "3"

volumes:
  _build:
  deps:
  gen:
services:
  glance:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - _build:/opt/app/_build
      - deps:/opt/app/deps
      # NOTE Issue Gleam shouldn't delete gen directory.
      # - gen:/opt/app/gen
    network_mode: host
    environment:
      PORT: 9000
      ENVIRONMENT: local
      SENTRY_DSN: https://e3b301fb356a4e61bebf8edb110af5b3@o351506.ingest.sentry.io/5574979
